package me.aroze.snuggles.commands

enum class Feelings(val feeling: String, val description: String, val messages: List<String>, val self: List<String> = listOf(), val bot: List<String> = listOf()) {
    HUG("hug", "Hugs a user", listOf(
        "{user} hugs {target}, awh.",
        "{user} gives {target} a big fat snuggly wuggly, these two are adorable.",
        "{user} tightly cuddles {target}. Look at these two, they're so cute together.",
        "{user} wraps their arms around {target} and gives them a warm, cozy hug.",
        "{user} pulls {target} in for a tight squeeze. These two are so affectionate!",
        "{user} showers {target} with affectionate hugs. It's clear these two have a special bond.",
        "{user} envelops {target} in a warm embrace, and it's clear they don't want to let go.",
        "{user} snuggles up to {target} for a loving hug. You can feel the warmth and affection between them.",
        "{user} hugs {target} so tightly, it's like they're trying to merge into one.",
        "{user} nuzzles into {target}'s neck for a sweet, intimate hug.",
        "{user} embraces {target} with a gentle, loving hug. It's clear how much they care for each other.",
        "{user} wraps {target} up in a warm, fuzzy hug. You can't help but feel happy watching these two interact.",
        "{user} gives {target} a hug that's filled with so much love, it's almost overwhelming.",
        "With a big smile, {user} embraces {target} in a warm hug.",
        "As {user} hugs {target}, they exchange a knowing look - these two have a special bond.",
        "It's hard not to smile as you watch {user} share a cozy hug with {target}.",
        "As {user} embraces {target}, you can feel the love and warmth radiating between them.",
        "With a gentle touch, {user} draws {target} in for a comforting hug.",
        "There's something so sweet and genuine about the way {user} hugs {target}.",
        "As {user} wraps their arms around {target}, you can tell {target} feels safe and loved in their embrace.",
        "Watching {user} hug {target} feels like watching two puzzle pieces fit together perfectly.",
        "You can't help but feel your own heart swell with warmth as {user} shares a loving embrace with {target}.",
        "There's no denying the bond between {user} and {target} as {user} hugs them - it's like they were made for each other.",
    ),
        listOf(
            "I understand you're desperate for affection, but you can't hug yourself, you idiot.",
            "Whilst I appreciate the sentiment, you can't hug yourself, you moron.",
            "Find another human to hug, you pathetic loser.",
            "What is wrong with you? Did you really just try to hug yourself? You're a fucking idiot.",
        ),
        listOf(
            "Don't touch me, you whore.",
            "Get your disgusting ass hands off of me, little bitch.",
            "Go hug a human, you desperate slut."
        )
    ),

    POKE("poke", "Pokes your victim", listOf(
        "{user} playfully pokes {target} with a grin on their face.",
        "{user} pokes {target} and laughs, clearly enjoying the playful moment.",
        "With a mischievous glint in their eye, {user} pokes {target} and tries to stifle a giggle.",
        "{user} gently pokes {target} on the arm, enjoying the light-hearted moment.",
        "With a quick poke, {user} gets {target}'s attention and flashes them a smile.",
        "{user} reaches out and pokes {target}, just trying to add a bit of fun to the day.",
        "As {user} pokes {target}, they share a laugh and enjoy the moment of levity.",
        "With a playful poke, {user} lets {target} know they're thinking of them.",
        "As {user} pokes {target} on the side, they can't help but laugh at the silly moment.",
        "With a poke on the shoulder, {user} reminds {target} that they're always there for them.",
        "{user} pokes {target} and makes a silly face, clearly in the mood for some fun.",
        "As {user} pokes {target}, they break out into a playful dance, drawing laughter from everyone around.",
        "With a ticklish poke, {user} sends {target} into a fit of giggles.",
        "With a playful poke, {user} teases {target} and invites them to join in on the fun.",
        "{user} pokes {target} and then runs away, daring them to try and catch them.",
        "With a quick poke and a wink, {user} hints at the playful shenanigans to come.",
        "As {user} pokes {target} more and more, they both burst into uncontrollable laughter.",
        "With a series of playful pokes, {user} and {target} engage in a lighthearted game of poking tag.",
        "{user} pokes {target} and then jumps back, ready for a round of playful banter.",
        "With a silly voice and a playful poke, {user} reminds {target} that life's too short to be serious all the time."
    ),
        listOf(
            "Awwwh you wanna poke yourself? That's so cute.",
            "Since you get 0 bitches, you've settled for poking yourself, honestly that's so sad.",
            "Yikes, mf tried poking themselves. Find someone else, you maidenless, lonely bitch.",
            "Go play with yourself elsewhere, that's so gross.",
        ),
        listOf(
            "Aint nobody poking me. Eat shit, stub your toe and cry.",
            "Did you really think I wouldn't notice you trying to poke me? You're fucking pathetic.",
            "I'm not a toy, back the fuck off.",
            "Ahah. hahhaha. haha. hah. I'm gonna poke YOU!",
            "You're a fucking idiot, you know that? You can't poke me, you moron.",
        )
    ),

    LICK("lick", "Use this to lick your prey ;)", listOf(
        "{user} sneakily licks {target}'s nose, so adorable!",
        "{user} affectionately licks {target}'s face, what a sweetie!",
        "{user} curiously licks {target}'s ear, how silly!",
        "{user} gives {target} a friendly lick, making everyone in the room feel awkward!",
        "{user} slobbers all over {target}'s face, proving that dogs really are man's best friend.",
        "{user} licks {target} as a sign of affection, or maybe just because they taste like bacon.",
        "{user} gives {target} a loving lick, leaving a slobbery surprise that will make them think twice before leaving food out again.",
        "{user} playfully licks {target}, proving that sometimes the best way to show love is through a wet, sloppy kiss.",
        "{user} enthusiastically licks {target}, as if they were a tasty popsicle on a hot summer day.",
        "{user} licks {target} like it's their job, leaving them wondering if they should be paying for this kind of service.",
        "{user} gives {target} a big, slobbery kiss that makes them feel like they just got slimed by a giant snail.",
        "{user} licks {target} so much that they start to wonder if they've been mistaken for a giant lollipop.",
        "{user} licks {target} as if their life depends on it, which is a good thing, because it's the only way they'll get their daily dose of affection.",
        "{user} licks {target} with such enthusiasm, it's like they're trying to give them a full-body bath with their tongue.",
        "{user} takes licking {target} to a whole new level, proving that they're the ultimate multitasker by simultaneously giving kisses and cleaning up spills.",
        "{user} licks {target} as if they were a toad, which is both adorable and a little bit gross at the same time.",
        "{user} licks {target} so much, they start to feel like they're part of a bizarre ASMR video.",
        "{user} gives {target} a few playful licks, reminding them that sometimes the best things in life are a little bit messy.",
        "{target} giggles as {user} licks their nose, tickling them in the process.",
        "{user} gives {target} a gentle lick on the hand, showing their appreciation for a good scratch.",
        "{target} can't help but smile as {user} gives them a loving lick on the cheek.",
        "{user} licks {target}'s forehead, leaving behind a wet spot and a feeling of warmth.",
        "{target} laughs as {user} playfully licks their toes, tickling them in the process.",
        "{user} gives {target} a few affectionate licks on the neck, showing their love in a unique way.",
        "{target} feels loved and comforted as {user} licks their hair, almost like a grooming ritual.",
        "{user} licks {target}'s arm, leaving behind a trail of slobber and a feeling of closeness.",
        "{target} playfully scolds {user} for giving them a slobbery lick on the nose, but secretly loves the attention.",
        "{user} gives {target} a few playful licks on the ear, making them feel like they have a furry little companion.",
    ),
        listOf(
            "Awwwh, you wanna lick yourself? That's so cute.",
            "Licking yourself is kinda weirddd, find someone else to smear your saliva on!",
            "Stop licking yourself, go put your so called brain to use.",
            "Woah there, what are you doing.",
            "Shouldd I let you lick yourselff? Hmmm, mmmm, no.",
        ),
        listOf(
            "Your breath stinks, get it the fuck away from me.",
            "Aint no way bro just tried to lick me.",
            "Do you have a licking kink?? Aw, cute. But I'm not the one. Sorry, not sorry.",
            "Go lick yourself.",
            "Go lick someone else, or I'm gonna start licking you. Jk, you wish. You desperate little bitch."
        )
    ),

    SLAP("slap", "slaps your victim", listOf(
        "{user} grabs {target} and slaps them so hard, it echoes through the room.",
        "{user} grabs {target}'s face and viciously slaps them with all their might.",
        "{user} throws out their hand and slaps {target} hard enough to make their ears ring.",
        "{user} delivers a harsh, violent slap to {target}'s face.",
        "{user} slaps {target} with a loud crack, leaving a deep red mark on their skin.",
        "{user} smacks {target} with a loud, sharp slap, making them yelp in pain and curse.",
        "{user} grabs {target} and sends them flying with a hard slap.",
        "{user} delivers an aggressive, brutal slap to {target}'s cheek.",
        "{user} punches {target} in the face and yells profanities at them.",
        "{user} slaps {target} with enough force to make them stumble back.",
        "{user} screams obscenities at {target} before delivering a powerful, angry slap.",
        "{user} delivers a hard, violent slap that leaves a deep red mark on {target}'s skin.",
        "{user} slaps {target} with a loud thud, leaving a deep red mark on their face.",
        "{user} knocks {target} out with a hard slap.",
        "{user} grabs {target}'s face and violently slaps them with all their strength.",
        "{user} slaps {target} hard enough to make them see stars.",
        "{user} delivers a harsh, vicious slap to {target}'s face.",
        "{user} smacks {target} with a loud, sharp slap, making them yelp in pain and swear.",
        "{user} knocks {target} off their feet with a hard slap.",
        "{user} delivers an intense, brutal slap to {target}'s cheek.",
        "{user} punches {target} hard in the face and calls them demeaning names.",
        "{user} slaps {target} with enough force to make them fall down.",
        "{user} screams expletives at {target} before delivering a fierce, angry slap.",
        "{user} delivers a hard, violent slap that leaves a burning red mark on {target}'s skin.",
        "{user} slaps {target} with a loud thud, leaving a deep red welt on their face.",
        "{user} slaps {target} so hard, it leaves them dazed.",
        "{user} brutally slaps {target}'s face with all their strength.",
        "{user} slaps {target} hard enough to make them deafen.",
        "{user} delivers a harsh, vicious slap to {target}'s face with a string of curses.",
        "{user} smacks {target} with a loud, sharp slap, making them yelp in pain and swear profusely.",
        "{user} knocks {target} unconscious with a hard slap.",
        "{user} delivers an aggressive, brutal slap to {target}'s cheek with a string of curses.",
        "{user} punches {target} in the face and shouts a slur at them.",
        "{user} slaps {target} with enough force to make them fall to their knees.",
        "{user} screams obscenities at {target} before delivering a fierce, violent slap.",
        "{user} slaps {target} with a loud crack, leaving a red mark on their cheek.",
        "{user} gives {target} a hard slap across the face.",
        "{user} slaps {target} so hard, the sound echoes through the room.",
        "{user} throws their hand out and lands a hard slap on {target}'s face.",
        "{user} grabs {target} by the collar and delivers an angry slap to their face.",
        "{user} slaps {target} with so much force, it sends them reeling.",
        "{user} grabs {target}'s face and slaps them with all their might.",
        "{user} delivers an aggressive slap to {target}'s cheek, followed by a stern look.",
        "{user} smacks {target} with a loud slap, making them yelp in pain.",
        "{target} recoils in shock as {user} slaps them hard.",
        "{user} delivers a stinging slap to {target}'s face.",
        "{user} makes a loud, sharp sound as they slap {target}.",
        "{target} cries out in pain as {user} violently slaps them.",
        "{user} quickly throws their hand out and slaps {target} in the face.",
        "{user} grabs {target}'s collar and delivers a sharp slap to their face.",
        "{target} jumps back in surprise as {user} slaps them hard.",
        "{user} strikes {target} across the face with an open palm, leaving a searing pain in their cheek.",
        "{user} delivers a resounding slap to {target}'s cheek, causing their head to jerk to the side.",
        "{user} snaps their hand forward, slapping {target} with a force that rattles their teeth.",
        "{user} whips their hand through the air, landing a sharp slap on {target}'s face that leaves a red welt.",
        "{user} smacks {target} hard in the face, causing their eyes to water and their nose to bleed.",
        "{user} raises their hand and delivers a resolute slap to {target}'s cheek, showing their disapproval.",
        "{user} lands a swift and powerful slap to {target}'s face, causing a loud crack to echo through the room.",
        "{user} swings their hand with purpose, striking {target} on the cheek with a loud thwack.",
        "{user} sharply slaps {target} across the face, causing their head to whip around and their eyes to widen in shock.",
        "{user} delivers a firm and audible slap to {target}'s face, leaving behind a stinging sensation and a faint red mark.",
        "The sound of flesh meeting flesh echoes through the room as {user} lands a hard slap on {target}'s cheek.",
        "{user} delivers a sharp blow to {target}'s face, leaving a handprint that slowly turns red.",
        "Without warning, {user} strikes {target} across the face with an open palm, sending them stumbling backwards.",
        "In a fit of rage, {user} slaps {target} so hard that their head snaps to the side.",
        "{user} backhands {target} with a resounding crack, leaving a red mark on their cheek.",
        "With a quick, decisive motion, {user} slaps {target} across the face, leaving them dazed and disoriented.",
        "{user} smacks {target} with an open palm, causing their head to whip around.",
        "Without a word, {user} delivers a stinging slap to {target}'s face, leaving them reeling.",
        "With a look of disgust, {user} slaps {target} across the face, making them flinch.",
        "{user} lands a solid slap on {target}'s cheek, causing them to stumble backwards in shock."
    ),
        listOf(
            "Why would you even think of slapping yourself? That's just sad.",
            "You think slapping yourself will make you feel better? You're a joke.",
            "What did you do to deserve a slap? You're a fucking loser.",
            "You really want to slap yourself, you masochistic piece of shit?",
            "Go ahead and slap yourself if you want, it won't make a difference anyway.",
            "Slapping yourself won't make the pain go away, you fucking moron.",
            "What, you think slapping yourself will help? You're an idiot.",
            "Slapping yourself, are you trying to hurt yourself? You're a fucking loser.",
            "You're so desperate for attention you're trying to slap yourself? That's pathetic.",
            "Go ahead and slap yourself, it won't hurt any more than your feelings already are."
        ),
        listOf(
            "I dare you to try and slap me. Just try it, I dare you.",
            "What the fuck? You really think you can just come up and slap me like that?",
            "You want a slap? Come get it.",
            "You want to slap me, huh? Let's go!",
            "I'm gonna slap you so hard you'll be seeing stars for weeks.",
            "You're lucky I don't slap you right now, you little shit.",
            "I'm gonna knock you the fuck out if you ever try to slap me again.",
            "I'm not a punching bag, back off before I slap you!",
            "You even think about slapping me and I'll fucking end you.",
            "Try it and see what happens. I promise you won't like it."
        )
    )

    // TODO: Slap, high five, yell, facepalm, bite, shake, stab, murder, dab, cry, pat

    // Template:

    //    ACTION("action", "whatever", listOf(
    //        ""
    //    ),
    //        listOf(),
    //        listOf()
    //    )

}